const assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
function totp(secret,offset=0){
    const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    let bits='';for(const char of secret.toUpperCase())bits+=alphabet.indexOf(char).toString(2).padStart(5,'0');
    const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));
    const count=Buffer.alloc(8);count.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)+offset));
    const h=crypto.createHmac('sha1',Buffer.from(bytes)).update(count).digest(),pos=h[19]&15;
    return ((h.readUInt32BE(pos)&0x7fffffff)%1000000).toString().padStart(6,'0');
}
module.exports=async({page,context,browser,base,password,root})=>{
    const route=(page,id)=>base+'/index.php?page='+page+(id?'&id='+id:'');
    const token=async(ctx)=>(await (await ctx.request.get(route('dashboard'))).text()).match(/name="csrf" value="([^"]+)"/)[1];
    const post=async(ctx,page,data,id)=>ctx.request.post(route(page,id),{form:{csrf:await token(ctx),...data}});
    const login=async(username)=>{
        const ctx=await browser.newContext({viewport:{width:1100,height:950}}),tab=await ctx.newPage();
        await tab.goto(route('login'));await tab.getByLabel('Username',{exact:true}).fill(username);await tab.getByLabel('Password',{exact:true}).fill(password);await tab.getByRole('button',{name:'Sign in',exact:true}).click();
        return {ctx,tab};
    };
    await post(context,'user-edit',{username:'securitypm',display_name:'Security PM',role:'pm',active:'1',password});
    await page.goto(route('users'));
    const pmId=new URL(await page.getByRole('link',{name:'Edit Security PM',exact:true}).getAttribute('href'),base).searchParams.get('id');
    const adminId=new URL(await page.getByRole('link',{name:'Edit Administrator',exact:true}).getAttribute('href'),base).searchParams.get('id');
    const pm=await login('securitypm');
    await pm.tab.getByRole('link',{name:'Users',exact:true}).click();
    assert.equal(await pm.tab.getByRole('link',{name:'Edit Administrator',exact:true}).count(),0);
    for(const id of [adminId,pmId]){
        assert.equal((await pm.ctx.request.get(route('user-edit',id))).status(),403);
        assert.equal((await post(pm.ctx,'user-edit',{username:'hacked',display_name:'No',role:'contractor',active:'1'},id)).status(),403);
        assert.equal((await post(pm.ctx,'user-mfa-reset',{id,password,confirmed:'1'})).status(),403);
    }
    assert.equal((await post(pm.ctx,'user-edit',{username:'badadmin',display_name:'No',role:'admin',password,active:'1'})).status(),403);
    await pm.tab.goto(route('user-edit'));
    assert.deepEqual(await pm.tab.getByLabel('Role',{exact:true}).locator('option').evaluateAll(options=>options.map(o=>o.value)),['contractor','contractor_admin']);
    await pm.tab.getByLabel('Display name',{exact:true}).fill('MFA Worker');
    await pm.tab.getByLabel('Username',{exact:true}).fill('mfaworker');
    await pm.tab.getByLabel('Password',{exact:true}).fill(password);
    await pm.tab.getByRole('button',{name:'Create user',exact:true}).click();
    const workerId=new URL(await pm.tab.getByRole('link',{name:'Edit MFA Worker',exact:true}).getAttribute('href'),base).searchParams.get('id');
    const worker=await login('mfaworker'),older=await login('mfaworker');
    await worker.tab.getByRole('link',{name:'Account security — set up MFA',exact:true}).click();
    await worker.tab.getByLabel('Current password',{exact:true}).fill(password);
    await worker.tab.getByRole('button',{name:'Set up MFA',exact:true}).click();
    assert(await worker.tab.locator('.mfa-qr').evaluate(img=>img.complete&&img.naturalWidth>0));
    const secret=await worker.tab.locator('.mfa-secret').textContent();
    await worker.tab.getByLabel('Authenticator code',{exact:true}).fill(totp(secret));
    await worker.tab.getByRole('button',{name:'Enable MFA',exact:true}).click();
    const codes=await worker.tab.locator('.recovery-codes code').allTextContents();
    assert.equal(codes.length,8);
    assert.equal(await worker.tab.locator('.mfa-notice').count(),0);
    await older.tab.goto(route('dashboard'));
    await older.tab.getByRole('heading',{name:'Welcome back',exact:true}).waitFor();
    await pm.tab.goto(route('users'));
    assert((await pm.tab.locator('tr',{hasText:'MFA Worker'}).innerText()).includes('Enabled'));
    await worker.tab.getByRole('button',{name:'Sign out',exact:true}).click();
    await worker.tab.getByLabel('Username',{exact:true}).fill('mfaworker');await worker.tab.getByLabel('Password',{exact:true}).fill(password);await worker.tab.getByRole('button',{name:'Sign in',exact:true}).click();
    await worker.tab.getByRole('heading',{name:'Verify your sign-in',exact:true}).waitFor();
    await worker.tab.goto(route('stores'));assert(worker.tab.url().includes('mfa-login'));
    await worker.tab.getByLabel('Authenticator or recovery code',{exact:true}).fill('invalid');
    await worker.tab.getByRole('button',{name:'Verify and sign in',exact:true}).click();
    assert(await worker.tab.getByRole('alert').isVisible());
    await worker.tab.getByLabel('Authenticator or recovery code',{exact:true}).fill(totp(secret,1));
    await worker.tab.getByRole('button',{name:'Verify and sign in',exact:true}).click();
    await worker.tab.getByRole('heading',{name:'Your workspace is ready',exact:true}).waitFor();
    await worker.tab.getByRole('button',{name:'Sign out',exact:true}).click();
    await worker.tab.getByLabel('Username',{exact:true}).fill('mfaworker');await worker.tab.getByLabel('Password',{exact:true}).fill(password);await worker.tab.getByRole('button',{name:'Sign in',exact:true}).click();
    await worker.tab.getByLabel('Authenticator or recovery code',{exact:true}).fill(codes[0]);
    await worker.tab.getByRole('button',{name:'Verify and sign in',exact:true}).click();
    await worker.tab.getByRole('heading',{name:'Your workspace is ready',exact:true}).waitFor();
    await pm.tab.goto(route('user-edit',workerId));
    await pm.tab.getByLabel('Your current password',{exact:true}).fill(password);
    await pm.tab.getByLabel('I confirm that MFA should be reset for this user.',{exact:true}).check();
    await pm.tab.getByRole('button',{name:'Reset MFA',exact:true}).click();
    await pm.tab.locator('.notice.success').waitFor();
    await worker.tab.reload();await worker.tab.getByRole('heading',{name:'Welcome back',exact:true}).waitFor();
    await worker.tab.getByLabel('Username',{exact:true}).fill('mfaworker');await worker.tab.getByLabel('Password',{exact:true}).fill(password);await worker.tab.getByRole('button',{name:'Sign in',exact:true}).click();
    await worker.tab.getByRole('heading',{name:'Your workspace is ready',exact:true}).waitFor();
    assert(await worker.tab.locator('.mfa-notice').isVisible());
    await worker.tab.setViewportSize({width:390,height:844});
    await worker.tab.getByRole('link',{name:'Account security — set up MFA',exact:true}).click();
    assert(await worker.tab.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await worker.tab.screenshot({path:path.join(root,'storage/security-mobile.png'),fullPage:true});
    for(const account of [pm,worker,older])await account.ctx.close();
    await page.goto(route('dashboard'));
    console.log('PASS: PM user scope, MFA QR enrollment, login gate, authenticator/recovery verification, reset and session revocation.');
};
