<div class="page-heading"><div><div class="eyebrow">STORES</div><h1><?= $id?'Edit store':'Create store' ?></h1><p>New stores receive a snapshot of all active global task templates.</p></div><a class="button" href="<?= e(url('stores')) ?>">Back to stores</a></div>
<form class="panel user-form" method="post" action="<?= e(url('store-edit',$id?['id'=>$id]:[])) ?>"><?= csrf() ?>
<div class="form-grid">
<?php foreach(['code'=>['Store code',40,true],'name'=>['Store name',160,true],'city'=>['City',120,true],'target_date'=>['Installation date',10,false]] as $key=>$field): ?>
<label><?= e($field[0]) ?><input name="<?= e($key) ?>" aria-label="<?= e($field[0]) ?>" type="<?= $key==='target_date'?'date':'text' ?>" maxlength="<?= $field[1] ?>" <?= $field[2]?'required':'' ?> value="<?= e($form[$key]??'') ?>"></label><?php endforeach; ?>
<label class="wide">Contracting company<select name="company_id" id="store-company" aria-label="Contracting company"><option value="">Unassigned</option><?php foreach($project->companies() as $company): if(!$company['active'])continue; ?><option value="<?= e($company['id']) ?>" <?= ($form['company_id']??'')===$company['id']?'selected':'' ?>><?= e($company['name']) ?></option><?php endforeach; ?></select></label>
<fieldset class="wide assignment-box"><legend>Individual contractors</legend><p class="muted">Choose contractors from this company. Its contractor admins can see every company store automatically.</p>
<?php foreach($contractors as $contractor): ?><label class="checkbox-label contractor-option" data-company="<?= e($contractor['company_id']) ?>"><input type="checkbox" name="contractors[]" value="<?= e($contractor['id']) ?>" <?= in_array($contractor['id'],$selected,true)?'checked':'' ?>><?= e($contractor['display_name']) ?></label><?php endforeach; ?><p class="muted contractor-hint">Select a company to show its available contractors.</p></fieldset>
</div><h2 class="section-heading">Store owner</h2><div class="form-grid">
<?php foreach(['owner_name'=>'Owner name','owner_phone'=>'Owner phone','owner_email'=>'Owner email'] as $key=>$label): ?><label><?= e($label) ?><input name="<?= e($key) ?>" aria-label="<?= e($label) ?>" type="<?= str_ends_with($key,'email')?'email':'text' ?>" maxlength="<?= str_ends_with($key,'email')?254:(str_ends_with($key,'phone')?60:120) ?>" <?= $key==='owner_name'?'required':'' ?> value="<?= e($form[$key]??'') ?>"></label><?php endforeach; ?></div>
<h2 class="section-heading">Store contact <span class="muted">(optional)</span></h2><div class="form-grid">
<?php foreach(['contact_name'=>'Contact name','contact_phone'=>'Contact phone','contact_email'=>'Contact email'] as $key=>$label): ?><label><?= e($label) ?><input name="<?= e($key) ?>" aria-label="<?= e($label) ?>" type="<?= str_ends_with($key,'email')?'email':'text' ?>" maxlength="<?= str_ends_with($key,'email')?254:(str_ends_with($key,'phone')?60:120) ?>" value="<?= e($form[$key]??'') ?>"></label><?php endforeach; ?></div>
<h2 class="section-heading">Installation reminder</h2><div class="form-grid"><label>Reminder date override<input type="date" name="reminder_date" aria-label="Reminder date override" value="<?= e($form['reminder_date']??'') ?>"><small>Leave empty to use the global schedule: <?= $project->reminderDays() ?> days before installation.</small></label></div>
<label class="checkbox-label"><input type="checkbox" name="reminders_enabled" <?= ($form['reminders_enabled']??false)?'checked':'' ?>>Enable reminders to the owner and contact email addresses</label>
<div class="form-actions"><button class="button primary">Save store</button></div></form>
