<div class="page-heading"><div><div class="eyebrow"><?= e($store['code']) ?> · <?= e($store['city']) ?></div><h1><?= e($store['name']) ?></h1><p>Installation: <?= e($store['target_date']?:'Not scheduled') ?> · <?= count($steps) ?> checklist steps</p></div><div class="button-group"><a class="button" href="<?= e(url('store-report',['id'=>$store['id']])) ?>" target="_blank" rel="noopener">Report preview</a><?php if(Access::atLeast($user,'pm')): ?><a class="button primary" href="<?= e(url('store-edit',['id'=>$store['id']])) ?>">Edit store</a><?php endif; ?></div></div>
<div class="store-summary"><section class="panel summary-card"><h2>Store owner</h2><strong><?= e($store['owner_name']?:'Not set') ?></strong><p><?= e($store['owner_phone']?:'—') ?></p><p><?= e($store['owner_email']?:'No email') ?></p></section><section class="panel summary-card"><h2>Store contact</h2><strong><?= e($store['contact_name']?:'Not set') ?></strong><p><?= e($store['contact_phone']?:'—') ?></p><p><?= e($store['contact_email']?:'No email') ?></p></section><section class="panel summary-card"><h2>Installation team</h2><strong><?= e(($project->rows('SELECT name FROM companies WHERE id=?',[$store['company_id']??''])[0]['name']??'No company assigned')) ?></strong><p><?= e(implode(', ',array_column($assigned,'display_name'))?:'No individual contractors assigned') ?></p></section></div>
<?php require __DIR__.'/store-unifi.php'; ?>
<section class="step-list" aria-label="Installation checklist">
<?php foreach($steps as $step): ?>
<article class="panel step-card" id="step-<?= e($step['id']) ?>"><div class="panel-heading"><div><span class="eyebrow"><?= e(ProjectRepository::CATEGORIES[$step['category']]) ?></span><h2><?= e($step['title']) ?></h2></div><span class="badge <?= $step['signed_at']?'positive':($step['complete']?'warning':'neutral') ?>"><?= $step['signed_at']?'Signed off':($step['complete']?'Awaiting sign-off':'To do') ?></span></div><div class="step-content">
<p class="instructions"><?= nl2br(e($step['instructions'])) ?></p>
<?php if(!$step['signed_at']): ?>
<form method="post" enctype="multipart/form-data" action="<?= e(url('step-update',['id'=>$step['id']])) ?>" class="step-form"><?= csrf() ?><input type="hidden" name="action" value="save"><input type="hidden" name="version" value="<?= e($step['version']) ?>"><label>Notes<textarea name="note" rows="3" maxlength="20000" aria-label="Notes for <?= e($step['title']) ?>"><?= e($step['note']) ?></textarea></label><label class="checkbox-label"><input type="checkbox" name="complete" <?= $step['complete']?'checked':'' ?>>This subtask is complete</label><span class="completion-feedback field-help" aria-live="polite"></span><small class="field-help">Completion saves automatically. Use Save step for notes and photos.</small><label class="photo-picker">Attach photos<span class="button file-picker-button" aria-hidden="true">Choose photos</span><input class="sr-only file-picker-input" type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple aria-label="Photos for <?= e($step['title']) ?>"><span class="selected-files" aria-live="polite">No photos selected</span><small>Up to 6 JPEG, PNG, or WebP photos per save, 10 MB each.</small></label><div class="form-actions"><button class="button primary">Save step</button></div></form>
<?php else: ?><p class="saved-note"><?= nl2br(e($step['note']?:'No notes added.')) ?></p><?php endif; ?>
<div class="photo-grid"><?php foreach($subtasks->photos($step['id']) as $photo): ?><a href="<?= e(url('photo',['id'=>$photo['id']])) ?>" data-photo-lightbox><img src="<?= e(url('photo',['id'=>$photo['id']])) ?>" alt="<?= e($photo['original_name']) ?>" loading="lazy"></a><?php endforeach; ?></div>
<p class="field-help completion-details" <?= !$step['complete']?'hidden':'' ?>>Completed by <?= e($step['completed_name']?:'Unknown user') ?> · <?= e($step['completed_at']) ?></p>
<?php if($step['signed_at']): ?><p class="signoff-line"><?= icon('shield') ?>Signed off by <?= e($step['signed_name']) ?> · <?= e($step['signed_at']) ?></p><?php endif; ?>
<?php if(Access::atLeast($user,'pm')): ?><form method="post" action="<?= e(url('step-update',['id'=>$step['id']])) ?>" class="signoff-form" <?= !$step['complete']&&!$step['signed_at']?'hidden':'' ?>><?= csrf() ?><input type="hidden" name="version" value="<?= e($step['version']) ?>"><input type="hidden" name="action" value="<?= $step['signed_at']?'reopen':'signoff' ?>"><button class="button"><?= $step['signed_at']?'Reopen step':'Sign off step' ?></button></form><?php endif; ?>
</div></article><?php endforeach; ?>
<?php if(!$steps): ?><div class="panel empty-state"><h2>No checklist steps</h2><p>This store was created without active task templates.</p></div><?php endif; ?></section>
<?php if(Access::atLeast($user,'pm')): ?>
<?php require __DIR__.'/store-pm-notes.php'; ?>
<section class="panel manual-reminder-panel"><div class="panel-heading"><div><h2>Send reminder now</h2><p>Sends immediately to <?= e(implode(', ',array_unique(array_filter([$store['owner_email'],$store['contact_email']])) )?:'the store owner/contact (add email addresses first)') ?>.</p></div>
<form method="post" action="<?= e(url('store',['id'=>$store['id']])) ?>" data-email-submit><?= csrf() ?><input type="hidden" name="action" value="send-reminder"><input type="hidden" name="request_id" value="<?= e(bin2hex(random_bytes(16))) ?>"><button class="button primary">Send reminder now</button></form></div>
<p class="log-caption">Uses saved SMTP settings, regardless of the automatic reminder schedule or enabled switches. This does not cancel the scheduled reminder. Each manual send is recorded below.</p></section>
<section class="panel log-panel"><div class="panel-heading"><div><h2>Installation reminder log</h2><p><?= $store['reminders_enabled']?'Reminder due: '.e($project->reminderDate($store)?:'Not scheduled'):'Reminders are disabled for this store.' ?> · <?= $store['reminder_date']?'Store override':'Global schedule' ?></p></div></div><div class="table-scroll"><table><thead><tr><th>Recipient</th><th>Trigger</th><th>Due / sent manually</th><th>Status</th><th>Attempted (UTC)</th><th>Sent at (UTC)</th><th>Details</th></tr></thead><tbody><?php foreach($logs as $log): ?><tr><td><?= e($log['recipient']) ?></td><td><?= e($log['source']) ?><small><?= e($log['actor_name']??'') ?></small></td><td><?= e($log['scheduled_for']) ?></td><td><?= e($log['status']==='sent'?'Accepted by SMTP':$log['status']) ?></td><td><?= e($log['created_at']) ?></td><td><?= e($log['sent_at']?:'—') ?></td><td><?= e($log['error']?:'—') ?></td></tr><?php endforeach; ?></tbody></table><?php if(!$logs): ?><p class="empty-search">No email attempts recorded yet.</p><?php endif; ?></div><p class="log-caption">“Accepted by SMTP” confirms server acceptance, not inbox delivery. Verify delivery in SMTP2Go activity. Interrupted or failed attempts are not retried automatically.</p></section>
<?php endif; ?>
<section class="panel log-panel"><div class="panel-heading"><h2>Step history</h2></div><div class="table-scroll"><table><thead><tr><th>Step</th><th>Action</th><th>By</th><th>When (UTC)</th></tr></thead><tbody><?php foreach($audits as $audit): ?><tr><td><?= e($audit['title']) ?></td><td><?= e(['save'=>'Updated','signoff'=>'Signed off','reopen'=>'Reopened'][$audit['action']]??$audit['action']) ?></td><td><?= e($audit['actor_name']) ?></td><td><?= e($audit['created_at']) ?></td></tr><?php endforeach; ?></tbody></table><?php if(!$audits): ?><p class="empty-search">No step changes yet.</p><?php endif; ?></div></section>

<dialog class="photo-lightbox" aria-labelledby="lightbox-title">
<div class="lightbox-toolbar"><h2 id="lightbox-title">Photo preview</h2><button type="button" class="button lightbox-close">Close</button></div>
<div class="lightbox-stage"><button type="button" class="icon-button lightbox-prev" aria-label="Previous photo">←</button><img class="lightbox-image" alt=""><button type="button" class="icon-button lightbox-next" aria-label="Next photo">→</button></div>
<p class="lightbox-error" role="alert" hidden>Could not load this photo. Close the preview and reload the store.</p>
<div class="lightbox-caption"><span class="lightbox-filename"></span><span class="lightbox-count" aria-live="polite"></span></div>
</dialog>
