<div class="page-heading"><div><div class="eyebrow">ADMINISTRATION</div><h1>Import stores</h1><p>Match stores by their unique store code. Review all changes before importing.</p></div><a class="button" href="<?= e(url('store-import',['sample'=>1])) ?>"><?= icon('download') ?>Download sample CSV</a></div>
<section class="panel"><div class="panel-heading"><h2>Upload CSV</h2></div><form method="post" enctype="multipart/form-data" class="step-content step-form"><?= csrf() ?><input type="hidden" name="action" value="preview"><label class="photo-picker">Store CSV<span class="button file-picker-button" aria-hidden="true">Choose CSV</span><input type="file" name="csv" class="sr-only csv-picker-input" aria-label="Store CSV" accept=".csv,text/csv" required><span class="csv-selected" aria-live="polite">No CSV selected</span></label><p class="field-help">Required: code, name, post_code, city. All Create Store fields are available. Use UTF-8 CSV with comma, semicolon, or tab separators, up to 1,000 rows / 2 MB. Keep codes and post codes as text to preserve leading zeros.</p><p class="field-help">Use existing contracting company names in company, and contractor usernames separated by | in contractors. Dates use YYYY-MM-DD. reminders_enabled accepts 1 or 0. Blank optional cells preserve existing values; for new stores they stay empty, with reminders enabled by default. Imports never send reminders.</p><div class="form-actions"><button class="button primary">Preview import</button></div></form></section>
<?php if($importDraft): ?>
<section class="panel import-preview"><div class="panel-heading"><div><h2>Review import</h2><p><?= count($importDraft['changes']) ?> <?= count($importDraft['changes'])===1?'store':'stores' ?> with changes · <?= $importDraft['ignored'] ?> unchanged rows ignored</p></div></div>
<?php foreach($importDraft['changes'] as $change): ?><section class="step-content"><h3><?= e($change['code']) ?> · <?= $change['id']?'Update existing store':'Create new store' ?></h3><div class="table-scroll"><table><thead><tr><th>Field</th><th>Current data</th><th>New data</th></tr></thead><tbody><?php foreach($change['diff'] as $field=>$values): ?><tr><th><?= e(ucfirst(str_replace('_',' ',$field))) ?></th><td><?= e($values['current']!==''?$values['current']:' - ') ?></td><td><?= e($values['new']!==''?$values['new']:' - ') ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endforeach; ?>
<div class="step-content"><p class="field-help">Nothing has been imported yet. Preview expires after 30 minutes. If source data changes, a new preview is required.</p><div class="import-actions">
<?php if($importDraft['changes']): ?><form method="post"><?= csrf() ?><input type="hidden" name="action" value="confirm"><input type="hidden" name="token" value="<?= e($importDraft['token']) ?>"><button class="button primary">Confirm import</button></form><?php endif; ?>
<form method="post"><?= csrf() ?><input type="hidden" name="action" value="cancel"><button class="button">Discard preview</button></form></div></div></section>
<?php endif; ?>
