<div class="page-heading"><div><div class="eyebrow">ADMINISTRATION / USERS</div><h1><?= e($title) ?></h1><p><?= isset($editing['id']) ? 'Update profile, role, and sign-in access.' : 'Give a team member access to the workspace.' ?></p></div><a class="button" href="<?= e(url('users')) ?>">Back to users</a></div>
<section class="panel form-panel"><div class="panel-heading"><h2>User details</h2><span class="pill"><?= icon('shield') ?><?= $user['role']==='admin'?'Admin':'Contractor accounts' ?></span></div>
<form method="post" class="user-form" action="<?= e(url('user-edit', isset($editing['id']) ? ['id' => $editing['id']] : [])) ?>">
<?= csrf() ?>
<div class="form-grid"><label>Display name<input name="display_name" maxlength="120" required value="<?= e($editing['display_name'] ?? '') ?>" autocomplete="off"></label><label>Username<input aria-label="Username" aria-describedby="username-help" name="username" maxlength="80" minlength="3" pattern="[a-zA-Z0-9._\-]{3,80}" required value="<?= e($editing['username'] ?? '') ?>" autocomplete="off"><small id="username-help">Letters, numbers, dots, underscores, and hyphens.</small></label><label>Email <span class="optional">(optional)</span><input aria-label="Email" name="email" type="email" maxlength="254" value="<?= e($editing['email'] ?? '') ?>" autocomplete="off"></label><label>Role<select name="role" aria-label="Role"><?php foreach (['contractor' => 'Contractor', 'contractor_admin'=>'Contractor admin', 'pm' => 'Project manager', 'admin' => 'Administrator'] as $value => $label): if($user['role']==='pm'&&!in_array($value,['contractor','contractor_admin'],true))continue; ?><option value="<?= e($value) ?>" <?= ($editing['role'] ?? 'contractor') === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Contracting company<select name="company_id" aria-label="Contracting company"><option value="">Unassigned (no contractor store access)</option><?php foreach($project->companies() as $company): if(!$company['active'])continue; ?><option value="<?= e($company['id']) ?>" <?= ($editing['company_id']??'')===$company['id']?'selected':'' ?>><?= e($company['name']) ?></option><?php endforeach; ?></select><small>Applies to contractors and contractor admins only.</small></label><label class="wide"><?= isset($editing['id']) ? 'New password' : 'Password' ?><input aria-label="Password" aria-describedby="password-help" type="password" name="password" minlength="8" maxlength="72" <?= isset($editing['id']) ? '' : 'required' ?> autocomplete="new-password"><small id="password-help"><?= isset($editing['id']) ? 'Leave empty to keep the current password. ' : '' ?>Use at least 8 characters (maximum 72 bytes).</small></label></div>
<label class="checkbox-label"><input type="checkbox" name="active" value="1" <?= ($editing['active'] ?? 1) ? 'checked' : '' ?>><span>Active account<small>Inactive users cannot sign in. Their records are preserved.</small></span></label>
<div class="form-actions"><a class="button" href="<?= e(url('users')) ?>">Cancel</a><button class="button primary" type="submit"><?= isset($editing['id']) ? 'Save changes' : 'Create user' ?></button></div>
</form></section>

<?php if(isset($editing['id'])&&$editing['id']): $mfaEnabled=$mfa->enabled($editing['id']); ?>
<section class="panel form-panel mfa-reset-panel"><div class="panel-heading"><h2>Multi-factor authentication</h2><span class="badge <?= $mfaEnabled?'positive':'warning' ?>"><?= $mfaEnabled?'Enabled':'Not enabled' ?></span></div>
<?php if($mfaEnabled): ?><form method="post" action="<?= e(url('user-mfa-reset')) ?>" class="user-form" data-mfa-reset><?= csrf() ?><input type="hidden" name="id" value="<?= e($editing['id']) ?>">
<p>Resetting removes this user's authenticator and recovery codes, and signs them out on all devices. They can then enroll again.</p>
<label class="mfa-password-label">Your current password<input type="password" name="password" autocomplete="current-password" required maxlength="72"></label>
<label class="checkbox-label"><input type="checkbox" name="confirmed" value="1" required>I confirm that MFA should be reset for this user.</label>
<div class="form-actions"><button class="button" type="submit">Reset MFA</button></div></form>
<?php else: ?><div class="user-form"><p>This user has not enabled MFA.</p></div><?php endif; ?></section>
<?php endif; ?>
